### ISSUE TITLE
App Path?

### ISSUE THREAD

**Issue by maximilianotaverna** [FydeOS/kiosk-demo-app#1]
Can you explain what this means..
_AppPath: relative path to the path of config file._

I have installed a chrome extension and I know the app id but what is the app path to confiig file?

**Comment by yunshansimon** [comment]
There is an example at [build](https://github.com/FydeOS/chromium_os-raspberry_pi/tree/r83/project-fyde-for-rpi/chromeos-base/fyde-kiosk-demo). The config file is at `/usr/local/share/kiosk_app`, your app should copy to `/usr/local/share/kiosk_app/${yourAppName}`, then modify the config file: 
```
{
  "AppId" : "${yourAppID}",
  "AppPath" : "${yourAppName}",
  "Enable" : true
}
```
Append the flag:  `--force-kiosk-mode` at the end of `/etc/chrome_dev.conf`

**Comment by maximilianotaverna** [comment]
Thankyou! my app is launching. two last questions,  is this kiosk mode logged in as a guest? will the device stay awake in this kiosk mode?
